import Link from "next/link"
import "./globals.css"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="flex flex-row justify-around p-4 my-2">
            <h1>Website</h1>
            <li>
              <Link href={"/docs"}>docs</Link>
            </li>
            <li>
              <Link href={"/blog"}>blog</Link>
            </li>
            <li>
              <Link href={"/showcase"}>showcase</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
